[BitTorrent]
Session\BTProtocol=Both
Session\DefaultSavePath=/downloads
Session\TempPath=/downloads/temp
Session\TempPathEnabled=true
Session\UseRandomPort=true
Session\Port=8999
Session\Interface=
Session\InterfaceName=

[Preferences]
WebUI\Username=admin
WebUI\Port=8080
WebUI\HostHeaderValidation=false
Connection\Interface=
Connection\InterfaceName=